import type { Metadata } from "next"
import { DM_Sans, Source_Sans_3 } from "next/font/google"
import "./globals.css"
import { ReactNode } from "react"

const DMSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
})

const SourceSans3 = Source_Sans_3({
  variable: "--font-source-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
    return (
        <html lang="en">
            <body className={`${DMSans.variable} ${SourceSans3.variable} antialiased`}>
                {children}
            </body>
        </html>
    )
}

export default RootLayout